{% set name = "mujoco" %}
{% set namecxx = "libmujoco" %}
{% set namepython = "mujoco-python" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/deepmind/mujoco/archive/refs/tags/{{ version }}.tar.gz
  sha256: b0108b44a4913c6d49a2fea382e684d10d0c43f51ac7d317d3c73fe66f120c33
  patches:
    - python_remove_avx.patch
    - cxx_devendor.patch
    - python_devendor.patch
    - ccd_vec3_origin_link_problem.patch
    - disable_copy_cxx_files_in_python_package.patch
    - do_not_install_via_pip.patch
    - unvendor_simulate.patch
    - workaround_cmake_19072.patch
    - 619bis.patch
    - simulate_unvendor_lodepng.patch

build:
  # See https://github.com/conda-forge/mujoco-feedstock/issues/22
  skip: true  # [(aarch64 or ppc64le or osx) and python_impl == 'pypy']
  number: 0

outputs:
  - name: {{ namecxx }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(namecxx, max_pin='x.x.x') }}
      # libabseil is used only for tests, we can 
      # safely ignore its run_exports
      ignore_run_exports:
        - libabseil
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make                                   # [not win]
        - ninja
        - clang                                  # [win]
        - lld                                    # [win]
        # This provides llvm-lib that is used during the linking
        - llvm-tools                             # [win]
      host:
        - eigen
        - qhull
        - tinyxml2
        - libccd-double
        - libabseil
        - lodepng
      run:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
      run_constrained:
        # Older version of this package were named mujoco-cxx, we want to avoid that they are installed
        - mujoco-cxx <0

    test:
      commands:
        - test -f ${PREFIX}/include/mujoco/mujoco.h  # [not win]
        - test -f ${PREFIX}/lib/libmujoco${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/bin/mujoco_plugin/libelasticity${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/bin/mujoco_plugin/libsensor${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/bin/mujoco_plugin/libsdf${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_INC%\\mujoco\\mujoco.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\mujoco.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\mujoco.dll exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\mujoco_plugin\\elasticity.dll exit 1  # [win]
        - if exist %LIBRARY_BIN%\\mujoco_plugin\\elasticity.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\mujoco_plugin\\sensor.dll exit 1  # [win]
        - if exist %LIBRARY_BIN%\\mujoco_plugin\\sensor.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\mujoco_plugin\\sdf.dll exit 1  # [win]
        - if exist %LIBRARY_BIN%\\mujoco_plugin\\sdf.lib exit 1  # [win]

  - name: {{ namepython }}
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make                                   # [not win]
        - ninja                                  # [win]
        - cmake
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pip                                    # [build_platform != target_platform]
        - setuptools                             # [build_platform != target_platform]
        - python-build                           # [build_platform != target_platform]
        - absl-py                                # [build_platform != target_platform]
        - clang                                  # [win]
        - lld                                    # [win]
        # This provides llvm-lib that is used during the linking
        - llvm-tools                             # [win]
        - bash                                   # [not win]
        - posix                                  # [win]
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
      host:
        - {{ pin_subpackage(namecxx, exact=True) }}
        - eigen
        - libabseil
        - python
        - pip
        - setuptools
        - python-build
        - pybind11
        - pybind11-abi
        - numpy
        - absl-py
        - glfw
        - pyglfw
        - pyopengl
        - xorg-libxfixes  # [linux]
      run:
        - {{ pin_subpackage(namecxx, exact=True) }}
        - python
        - numpy
        - absl-py
        - pyglfw
        - pyopengl
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
        # Transitive dependencies of etils[epath], not directly available on conda-forge
        - etils
        - fsspec
        - importlib_resources
        - typing_extensions
        - zipp
    test:
      imports:
        - mujoco
      requires:
        - pytest
        - pip
      commands:
        - pytest --pyargs mujoco -v -k "not render"
        - pip check

  - name: mujoco-mjx
    build:
      noarch: python
      script: python -m pip install ./mjx/ --no-deps -vv
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - jaxlib
        - jax
        - absl-py
        - scipy
        - trimesh
        - mujoco-python >={{ version }}
        # Transitive dependencies of etils[epath], not directly available on conda-forge
        - etils
        - fsspec
        - importlib_resources
        - typing_extensions
        - zipp
    test:
      imports:
        - mujoco.mjx
      requires:
        - pip
        - pytest
      commands:
        - pip check
        - pytest --pyargs mujoco.mjx -v

  - name: {{ name }}
    requirements:
      run:
        - {{ pin_subpackage(namecxx, exact=True) }}
        - {{ pin_subpackage(namepython, max_pin='x.x.x') }}
    test:
      imports:
        - mujoco

about:
  home: https://github.com/deepmind/mujoco
  license: Apache-2.0
  license_file:
    - LICENSE
    - build/_deps/tinyobjloader-src/LICENSE
    - build/_deps/sdflib-src/LICENSE
  summary: Multi-Joint dynamics with Contact. A general purpose multi-body dynamics simulator.

extra:
  recipe-maintainers:
    - traversaro
